### ISSUE TITLE
Move extension-content-operator chart to this repo

### ISSUE THREAD

**Issue by nexus49** [openmfp/helm-charts#20]
The extension content operator (to be renamed to be extension-manager-operator https://github.com/openmfp/extension-content-operator/issues/118) will be open sourced in the first version.

**Task**
- [x] Move the chart from helm-charts-priv to  
- [x] Prepare the chart for open sourcing
- [x] Extend description in chart.yaml: https://github.com/openmfp/helm-charts/blob/main/charts/extension-manager-operator/Chart.yaml#L3
- [x] delete and update references in helm-charts-priv
- [x] deploy server with `validation` endpoint
