### ISSUE TITLE
Move example-ui chart to this repo and rename to be example-content

### ISSUE THREAD

**Issue by nexus49** [openmfp/helm-charts#21]
The example-ui will be open sourced in the first version, it deploys the example-content repo.

A version of the example-content chart will remain in the private repo to deploy the apeirora branch

**Task**
- [x] copy the chart from helm-charts-priv to helm-charts
- [x] Rename chart to be example-content, matching the repo source
- [x] Prepare the chart for open sourcing
- [ ] Verify/adjust existing deployments

**Comment by nexus49** [comment]
This is complete
