### ISSUE TITLE
Move infra chart to this repo 

### ISSUE THREAD

**Issue by nexus49** [openmfp/helm-charts#24]
The infra chart will be open sourced in the first version.

**Task**

- [x] Move the chart from helm-charts-priv to helm-charts
- [x] Toggle off future aspects like kcp, fga, accounts and so on, but leave them in the chart
- [x] Prepare the chart for open sourcing
